language: swift
osx_image: xcode10
script: xcodebuild clean -project Source/UnderLineTextField.xcodeproj && xcodebuild build -project Source/UnderLineTextField.xcodeproj -scheme UnderLineTextField
branches:
  only:
  - master
xcode_project: UnderLineTextField.xcodeproj
xcode_scheme: UnderLineTextField
xcode_sdk: iphonesimulator12.0
env:
  global:
  - FRAMEWORK_NAME=UnderLineTextField
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
before_script: 
before_deploy:
- carthage build --no-skip-current
- carthage archive $FRAMEWORK_NAME
